apiVersion: apps/v1
kind: Deployment
metadata:
  name: springjenkins-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springjenkins-backend
  template:
    metadata:
      labels:
        app: springjenkins-backend
    spec:
      containers:
      - name: springjenkins-backend
        image: hanenlouati/mynginx:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springjenkins-service
spec:
  selector:
    app: springjenkins-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
